### ISSUE TITLE
craw_coronavirus not working

### ISSUE THREAD

**Issue by dickoa** [JohnCoene/coronavirus#1]
Hi John,

I'm so glad you built this package, I was thinking if something like that was possible this morning.
I tried to run the example from the `README` and got an error, is there something I'm missing

```r
> library(coronavirus)
> 
> # create and fill config file
> create_config()
✔ _coronavirus.yml file copied: fill it in
> crawl_coronavirus()
Error: could not translate host name "123.456.7.8" to address: Temporary failure in name resolution
```

Thanks again for this

**Comment by dickoa** [comment]
I will check the doc again regarding how to modify the yml file and will reopen it in case I don't find a solution.

**Comment by JohnCoene** [comment]
Thank you for this. It's a valid issue, it probably not clear that one has to fill in the config file.

**Comment by JohnCoene** [comment]
Are you at ease with Postgres, perhaps I should add possibility to use SQLite, much simpler to set up. What do you think?

**Comment by JohnCoene** [comment]
SQLite was not ideal anyways. So I came up with this. It'll let you test or dev without doing any kind of deploy or preparing a database.

:warning: If you had the `_coronavirus.yml` file created, delete it.

```r
library(coronavirus)

virus <- crawl_coronavirus()
run_app(virus)
```

Hope this works! Let me know :)

**Comment by dickoa** [comment]
It works perfectly and I just wanted to first test it. You did an amazing work!
Thanks again for this

**Comment by JohnCoene** [comment]
Thank for the the kind comment and taking the time to check it out :)

**Comment by HennieBez** [comment]
Hi, thank you very much for this amazing package - It is adding an incredible amount of value to our investment management process.

`crawl_coronavirus()` is not working on my side today (even though it worked the entire last week) due to the following error (I have no `_coronavirus.yml` file created on purpose) :

` Error in UseMethod("mutate_") : 
  no applicable method for 'mutate_' applied to an object of class "list"`

Will you please be able to advise ?

**Comment by JohnCoene** [comment]
Sorry, yes indeed. I'm currently weighing in the options, this is due to a data source/endpoint no longer returning data, I will look into this today and hope to have a solution tomorrow.

**Comment by JohnCoene** [comment]
It's fixed; reinstall the latest version.
