### ISSUE TITLE
date issue on api

### ISSUE THREAD

**Issue by atifamin** [JohnCoene/coronavirus#11]
```
    "data": [
        {
            "state": "Anhui",
            "country": "Mainland China",
            "lat": 31.8257,
            "lon": 117.2264,
            "type": "confirmed",
            "date": 18283,
            "cases": 1,
            "country_iso2c": "CN"
        }
     ]
```

I get this **date format 18283**, which I don't understand what is it, can you convert date into human format or you can tell what is format of date.

**Comment by johnlewissims** [comment]
Looks like they are using a Julian Date format.  Pretty standard practice to use some number-based date format like this or Unix Timestamp. I would recommend using [this](https://github.com/jonhester/julian-date) tool for converting it.

**Comment by JohnCoene** [comment]
Sorry, indeed this is how it was but accidental, I've just changed it.
