### ISSUE TITLE
crawl_coronavirus()

### ISSUE THREAD

**Issue by barthelmes** [JohnCoene/coronavirus#12]
Hi there, thanks for the package. An issue on initiation. Mazbe sources have been updated>
ℹ Crawling data from John Hopkins
ℹ Crawling data from Weixin
Error: lexical error: inside a string, '\' occurs before a character which it may not.
          howHeal\":true}}]},{\"name\":\ �� �� �� ��  Host: 127.0.
                     (right here) ------^
In addition: Warning message:
In countrycode::countrycode(country, "country.name", "iso2c") :
  Some values were not matched unambiguously: Others

**Comment by JohnCoene** [comment]
Interesting, I don't see that. Perhaps they have just made changes, would you mind retrying and letting me know if you still see that error?

**Comment by JohnCoene** [comment]
Have you had the time to check? Let me know so I can close if fixed.
