### ISSUE TITLE
try to run doocker file 

### ISSUE THREAD

**Issue by rashed-m-omar** [JohnCoene/coronavirus#13]
i have build the docker container and try to run it i got this error 

> Error : Missing config file, see `create_config`

**Comment by JohnCoene** [comment]
Yes, you will need to mount the config file, see [docs](https://coronavirus.john-coene.com/#/prod?id=docker), I will hopefully get rid of that in the future so that everything is in the container.

```bash
docker run -v "$(pwd)"/_coronavirus.yml:/_coronavirus.yml -p 3000:80 jcoenep/corona
```
