### ISSUE TITLE
After loading and parsing, run_app() returns some warnings, and cannot show charts

### ISSUE THREAD

**Issue by al00014** [JohnCoene/coronavirus#14]
I got the following errors:
Warning: Error in : 'e_hide_grid_lines' is not an exported object from 'namespace:echarts4r'

Warning: Error in : 'e_hide_grid_lines' is not an exported object from 'namespace:echarts4r'
  [No stack trace available]
Warning: Error in : 'e_hide_grid_lines' is not an exported object from 'namespace:echarts4r'
  [No stack trace available]

----------------------------- Line breaker--------------------------

With the following session info:
sessionInfo()
R version 3.6.2 (2019-12-12)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] shiny_1.4.0.1     coronavirus_0.1.3

**Comment by al00014** [comment]
It seems that the new version of echarts4r (installed by install.packages() with default setting) did not have the function e_hide_grid_lines().

**Comment by JohnCoene** [comment]
It was installing from Github but not enforcing the correct version. It's fixed now thank you.

**Comment by al00014** [comment]
Thank you!
