### ISSUE TITLE
echarts4r package

### ISSUE THREAD

**Issue by hp911** [JohnCoene/coronavirus#18]
Hi John,

Thank you so much for this! This looks great!

I installed via `remotes::install_github("JohnCoene/coronavirus")`

When I ran run_app(virus), the app panel complained that I did not have echarts4r package. When I installed that package, everything worked like a charm.

I guess somehow echarts4r package was not included.

Thanks!

_Henry

**Comment by JohnCoene** [comment]
Thanks Henry, I have put echarts4r on `Suggests` as it can be quite large but it might not make sense since it is necessary to running the dashboard. I'll consider moving it to `Imports`. Thanks.
