### ISSUE TITLE
Number of suspected cases for DXY data

### ISSUE THREAD

**Issue by Nelson-Gon** [JohnCoene/coronavirus#2]
Hello there,

I was taking a look at the [app](https://shiny.john-coene.com/coronavirus/) and noticed that the number of suspected cases for the DXY data was only 2(see pic below). 

This is I believe a bug as can be seen [here](https://ncov.dxy.cn/ncovh5/view/pneumonia)

Pic from the app ![](https://i.imgur.com/valFxy9.png)

**Comment by JohnCoene** [comment]
Yes, that's ugly. I scrape the data from DXY to get city-level data, where it actually says 2 suspected cases. This is, however, clearly inaccurate. I have thus just removed that data point for the time being. Thank you.

**Comment by Nelson-Gon** [comment]
Actually looking at it now(on phone), the recovered and deaths numbers are also swapped. The number of recoveries are more than the deaths since 04th Feb. The actual numbers are correct, just the labels.

**Comment by JohnCoene** [comment]
A very poor mistake from my part, apologies and thank you for pointing it out. I've added a [corrections section to the README](https://github.com/JohnCoene/coronavirus#corrections)

**Comment by JohnCoene** [comment]
Thanks, again. Feel free to submit any other issue you may spot. I'll close this for now.
