### ISSUE TITLE
function get_query

### ISSUE THREAD

**Issue by GuilhermeFCO** [JohnCoene/coronavirus#24]
Hi, I looked for which package the get_query() function is, but I couldn't find it. It is being used to remove the value of variables from the search url. If possible, help me, I am immensely grateful.

I'm find, sorry for this issue

**Comment by JohnCoene** [comment]
It's not exported

https://github.com/JohnCoene/coronavirus/blob/26fee62977b3dc9cbe8aef75503c47cd7f8fd652/R/embeds_server.R#L120

```r
coronavirus:::get_query
```
