### ISSUE TITLE
Package installation issue

### ISSUE THREAD

**Issue by liuliuball45** [JohnCoene/coronavirus#6]
I am trying to install the package through R studio.

I used the command below and got error message about encoding....wondering is there anything i need to do with my R environment setup?? Thanks if you can help.

> remotes::install_github("JohnCoene/coronavirus")
Downloading GitHub repo JohnCoene/coronavirus@master
√  checking for file 'C:\Users\liuli\AppData\Local\Temp\Rtmp8c7Ka9\remotes29e429787b42\JohnCoene-coronavirus-2bad348/DESCRIPTION' (572ms)
-  preparing 'coronavirus':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  looking to see if a 'data/datalist' file should be added
-  building 'coronavirus_0.0.3.tar.gz'
   
Installing package into ‘C:/Users/liuli/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
* installing *source* package 'coronavirus' ...
** R
Error : (converted from warning) unable to re-encode 'utils.R' lines 34, 35, 36, 37
ERROR: unable to collate and parse R files for package 'coronavirus'
* removing 'C:/Users/liuli/Documents/R/win-library/3.5/coronavirus'
In R CMD INSTALL
Error: Failed to install 'coronavirus' from GitHub:
  (converted from warning) installation of package ‘C:/Users/liuli/AppData/Local/Temp/Rtmp8c7Ka9/file29e44cc750/coronavirus_0.0.3.tar.gz’ had non-zero exit status

**Comment by JoeFernando** [comment]
same issue for me!

> sessionInfo()
R version 3.6.1 (2019-07-05)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] ps_1.3.0          prettyunits_1.0.2 withr_2.1.2.9000  crayon_1.3.4      rprojroot_1.3-2  
 [6] assertthat_0.2.1  R6_2.4.0          backports_1.1.4   magrittr_1.5      cli_1.1.0        
[11] curl_4.2          remotes_2.0.2     rstudioapi_0.10   callr_3.2.0       tools_3.6.1      
[16] compiler_3.6.1    processx_3.3.1    pkgbuild_1.0.3

**Comment by JohnCoene** [comment]
Thank you for reporting this!

Yes indeed, probably the encoding due to chinese characters. I have moved that to datasets so it passes all checks, I have tried myself, removing package and reinstalling from github and worked fine. Let me know.

```r
remotes::install_github("JohnCoene/coronavirus")
```

**Comment by JoeFernando** [comment]
still no luck. It installs but no luck thereafter:


> library(coronavirus) >  > virus <- crawl_coronavirus() i Crawling data from John Hopkins Error in loadNamespace(name) : there is no package called ‘curl’ > run_app(virus) Error in with_golem_options(app = shinyApp(ui = app_ui, server = app_server),  :    object 'virus' not found
--

**Comment by JohnCoene** [comment]
Re `there is no package called ‘curl’`, did you try to install the missing package `curl`?

```r
install.packages("curl")
```

**Comment by JoeFernando** [comment]
thanks....the crawl works. App failed:

 run_app(virus)

# This is what I see in the console
Listening on http://127.0.0.1:5373
Warning: Error in tag: argument is missing, with no default
  73: tag
  72: shiny::tags$div
  70: f7Col
  46: ui

Error in the app when it opened:
ERROR: argument is missing, with no default

**Comment by JoeFernando** [comment]
- Session info ------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_Australia.1252      
 ctype    English_Australia.1252      
 tz       Australia/Sydney            
 date     2020-02-09                  

- Packages ----------------------------------------------------------------------------------------------------------
 package       * version    date       lib source                                 
 assertthat      0.2.1      2019-03-21 [1] CRAN (R 3.5.3)                         
 attempt         0.3.0      2019-04-08 [1] CRAN (R 3.6.2)                         
 backports       1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                         
 cellranger      1.1.0      2016-07-27 [1] CRAN (R 3.5.0)                         
 cli             2.0.1      2020-01-08 [1] CRAN (R 3.6.2)                         
 colorspace      1.4-1      2019-03-18 [1] CRAN (R 3.6.1)                         
 commonmark      1.7        2018-12-01 [1] CRAN (R 3.6.2)                         
 coronavirus   * 0.0.3      2020-02-09 [1] Github (JohnCoene/coronavirus@a6fb73a) 
 countrycode     1.1.1      2020-02-08 [1] CRAN (R 3.6.1)                         
 countup         0.1.0      2020-02-09 [1] Github (JohnCoene/countup@c8f6cbe)     
 crayon          1.3.4      2017-09-16 [1] CRAN (R 3.5.0)                         
 curl            4.3        2019-12-02 [1] CRAN (R 3.6.2)                         
 desc            1.2.0      2018-05-01 [1] CRAN (R 3.5.3)                         
 digest          0.6.22     2019-10-21 [1] CRAN (R 3.5.3)                         
 dplyr           0.8.3      2019-07-04 [1] CRAN (R 3.5.3)                         
 fansi           0.4.0      2018-10-05 [1] CRAN (R 3.5.2)                         
 fs              1.3.1      2019-05-06 [1] CRAN (R 3.5.3)                         
 gargle          0.4.0      2019-10-04 [1] CRAN (R 3.6.2)                         
 ggplot2         3.2.1      2019-08-10 [1] CRAN (R 3.5.3)                         
 glue            1.3.1      2019-03-12 [1] CRAN (R 3.5.3)                         
 golem           0.1        2019-08-05 [1] CRAN (R 3.6.2)                         
 googlesheets4   0.1.0      2019-11-04 [1] CRAN (R 3.6.2)                         
 gtable          0.3.0      2019-03-25 [1] CRAN (R 3.5.3)                         
 htmltools       0.3.6      2017-04-28 [1] CRAN (R 3.5.0)                         
 htmlwidgets     1.2        2018-04-19 [1] CRAN (R 3.5.0)                         
 httpuv          1.5.2      2019-09-11 [1] CRAN (R 3.5.3)                         
 httr            1.4.1      2019-08-05 [1] CRAN (R 3.5.3)                         
 jsonlite        1.6        2018-12-07 [1] CRAN (R 3.5.2)                         
 later           0.8.0      2019-02-11 [1] CRAN (R 3.5.3)                         
 lazyeval        0.2.2      2019-03-15 [1] CRAN (R 3.5.3)                         
 lifecycle       0.1.0      2019-08-01 [1] CRAN (R 3.5.3)                         
 lubridate       1.7.4      2018-04-11 [1] CRAN (R 3.5.3)                         
 magrittr        1.5        2014-11-22 [1] CRAN (R 3.5.0)                         
 mime            0.7        2019-06-11 [1] CRAN (R 3.5.3)                         
 munsell         0.5.0      2018-06-12 [1] CRAN (R 3.5.3)                         
 nCov2019        0.0.6      2020-02-09 [1] Github (GuangchuangYu/nCov2019@b1b23be)
 pillar          1.4.2      2019-06-29 [1] CRAN (R 3.5.3)                         
 pkgconfig       2.0.2      2018-08-16 [1] CRAN (R 3.5.2)                         
 pkgload         1.0.2      2018-10-29 [1] CRAN (R 3.5.3)                         
 promises        1.0.1      2018-04-13 [1] CRAN (R 3.5.0)                         
 purrr           0.3.3      2019-10-18 [1] CRAN (R 3.6.1)                         
 R6              2.4.0      2019-02-14 [1] CRAN (R 3.5.3)                         
 Rcpp            1.0.3      2019-11-08 [1] CRAN (R 3.6.1)                         
 rlang           0.4.4      2020-01-28 [1] CRAN (R 3.6.2)                         
 roxygen2        6.0.1      2017-02-06 [1] CRAN (R 3.5.0)                         
 rprojroot       1.3-2      2018-01-03 [1] CRAN (R 3.5.0)                         
 rsconnect       0.8.13     2019-01-10 [1] CRAN (R 3.5.3)                         
 rstudioapi      0.10       2019-03-19 [1] CRAN (R 3.5.3)                         
 rvest           0.3.5      2019-11-08 [1] CRAN (R 3.5.3)                         
 scales          1.0.0      2018-08-09 [1] CRAN (R 3.5.3)                         
 selectr         0.4-1      2018-04-06 [1] CRAN (R 3.5.0)                         
 sessioninfo     1.1.1      2018-11-05 [1] CRAN (R 3.5.3)                         
 shiny         * 1.3.2      2019-04-22 [1] CRAN (R 3.5.3)                         
 shinyMobile     0.1.0      2019-11-30 [1] CRAN (R 3.6.2)                         
 stringi         1.4.3      2019-03-12 [1] CRAN (R 3.5.3)                         
 stringr         1.4.0      2019-02-10 [1] CRAN (R 3.5.3)                         
 testthat        2.0.0      2017-12-13 [1] CRAN (R 3.5.1)                         
 tibble          2.1.3      2019-06-06 [1] CRAN (R 3.5.3)                         
 tidyr           1.0.0      2019-09-11 [1] CRAN (R 3.6.1)                         
 tidyselect      0.2.5      2018-10-11 [1] CRAN (R 3.5.2)                         
 usethis         1.5.0      2019-04-07 [1] CRAN (R 3.5.3)                         
 utf8            1.1.3      2018-01-03 [1] CRAN (R 3.5.0)                         
 vctrs           0.2.2      2020-01-24 [1] CRAN (R 3.6.2)                         
 waiter          0.1.0      2020-01-14 [1] CRAN (R 3.6.2)                         
 withr           2.1.2.9000 2020-02-09 [1] Github (jimhester/withr@16d47fd)       
 xml2            1.2.2      2019-08-09 [1] CRAN (R 3.6.2)                         
 xtable          1.8-4      2019-04-21 [1] CRAN (R 3.5.3)                         
 yaml            2.2.0      2018-07-25 [1] CRAN (R 3.5.2)                         
 yesno           0.1.0      2018-04-14 [1] CRAN (R 3.5.0)

**Comment by JohnCoene** [comment]
Thank you very much for your patience Joseph, it seem it is because you're on the previous version of shiny `1.3.0`. I have added this to the `DESCRIPTION`. Reinstall the package should update shiny and subsequently work.

```r
remotes::install_github("JohnCoene/coronavirus")
```

Sorry again, let me know if this works.

**Comment by JoeFernando** [comment]
it worked!!! Thanks John.

**Comment by JohnCoene** [comment]
Not at all, thanks to you for all your patience and reporting this!

**Comment by cdriveraus** [comment]
I am getting a similar issue, presumably due to character set:
Error : (converted from warning) C:/Users/Driver/AppData/Local/Temp/RtmpI9Mnbw/R.INSTALL28a835e031ba/coronavirus/man/api.Rd:22: unknown macro '\Â'

**Comment by JohnCoene** [comment]
Sorry encoding issue, could please try again? and let me know.

**Comment by cdriveraus** [comment]
Yep no more warnings, fixed.

**Comment by JohnCoene** [comment]
Thank you for reporting this.
