### ISSUE TITLE
DXY name typo

### ISSUE THREAD

**Issue by Shu-Wan** [JohnCoene/coronavirus#7]
Hi, love this work.
I want to point out the correct [pinyin](https://en.wikipedia.org/wiki/Pinyin) of `丁香园` is `Ding Xiang Yuan` not `Ding Xiang Ying`.

**Comment by JohnCoene** [comment]
谢谢，对不起一我的真的中文不好！

**Comment by JohnCoene** [comment]
Fixed. 谢谢🙏
